language: ruby
cache: bundler

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "lion0303@hanyang.ac.kr"
  - git config --global user.name "GiveMeMandu"

script:
  - bundle exec rake site:deploy --quiet
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4.2

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'

env:
  global:
    secure: "yRT/eJT2E1pPtuQCx/xbWChT8I67nqnU7T0LkKbT+nflZ/LT7aIFPuPCsZURPu6aTaGOWQ+DL7Z1t0P1T3lMFnhG58wFOZsxCifM0l9j9yNR36DybYpLn/aNrs+n7h09Y8rXDGt619i7/wllpCRQeRdGh/RzKgXa6fv9SyqiEvvMjEC7w0s/FA22vElXueR3/N1QDsbDbqYEDjUEfJ5762flqFQvagprbPKT4bC9OHRPwNfuG5CJhmHlA0VGl51X70QI62mjDvaAiLAVI3rkpFYv7xMoVEMl388hDYEAP3uqq7TaOZHe/jB0X7vfJJy5GZvGSDzAaRxRCaRny9zqoKyiS3CRW8Qnzf0D6Cn7o+YYrM6B/qUzCCHGgTF83s51h76yPtgNOZ72O38pcyLhxE+xTebW/tBiIYGnii+huw5PhP4rM5mpZihQQrEa7XpD8Gi6Dpit92rPsBKCL+IlYN6kQSDCDWsEGvSsCz8BXymTX81ws72//RTLqUkHkF2Dokz/rSpi0+8HTYjLdMHn0HQu8eRR0jNX6Jye0ck8zNjwTNOP10I5Wyrbp2D2ZT1JJsksLQNOIIu8vAcIkb8FI0lCPcRkxXwWJIsQ2DuwbnH39uroxIcXvLBYWwCHWje2Gn3rOwwVIQ+aOIXrLd3VQFknTIPui8aiVIg/2Nm8pLk="
